<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Making CALL Raise a (definitional) Error For Bad Exit Codes</title>
    <link>https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068</link>
    <description>Before definitional errors existed, I noticed that [@gchiu had some uses of CALL](https://forum.rebol.info/t/the-need-to-rethink-error/1371/2?u=hostilefork) that weren&#39;t checking the return code.

    call [
        gs -sDEVICE=pngmono -o (join root &quot;-%02d.png&quot;) -r600 (pdfname)
    ]

    call [
        gs -sDEVICE=eps2write -sPAPERSIZE=a4
            -o (join root &quot;-%02d.eps&quot;) (pdfname)
    ]

I wanted the default to raise an error if the **gs** (GhostScript) process did not return a 0 exit code.  But I wanted that error to be a result of CALL... so it would be distinct from other errors (like a typo in the code in the groups inside, `pfdname` instead of `pdfname` or whatever).

`CALL` was already a wrapper on top of an internal `CALL*` function, so I thought &quot;why not expand upon that?&quot;

## A Cool ENCLOSE of an AUGMENT of a SPECIALIZE!

    call: enclose (
        augment (specialize :call* [wait: #]) [
            /relax &quot;If exit code is non-zero, return the integer vs. raising error&quot;
        ]
    ) func [f [frame!]] [
        let relax: f.relax
        let result: do f
        if relax or (result = 0) [
            return result
        ]
        return raise make error! compose [
            message: [&quot;Process returned non-zero exit code:&quot; exit-code]
            exit-code: (result)
        ]
    ]

I think that&#39;s pretty neat.

It twists the CALL* function so that it always waits (vs. spawn a separate process and return a process ID to wait on).

Then it offers a /RELAX setting for getting the exit code back, if you don&#39;t want the definitional error behavior.

But then, by default it will RAISE an error.   You can get that error via EXCEPT or you can do TRY CALL if you just want to ignore any errors.

## Issue Exposed: Who&#39;s Actually To Blame?

While making this I noticed that there were actually several points of failure:

* The guts of CALL might not be able to find the file you&#39;re asking to execute

* The executable may run, but return a non-zero exit code

* If you&#39;re running through CALL/SHELL and delegating to it to call a process, then the shell may have its own exit status distinct from the process you tried to call

It seems there&#39;s not really any great way to untangle the return results of a shell from that of a process it executes.  [Here&#39;s some of the informal conventions of UNIX shells](https://en.wikipedia.org/wiki/Exit_status):

&gt; *&quot;When a command is terminated by a signal whose number is N, a shell sets the variable $? to a value greater than 128. Most shells use 128+N, while ksh93 uses 256+N.&quot;*
&gt;
&gt; *&quot;If a command is not found, the shell should return a status of 127. If a command is found but is not executable, the return status should be 126.&quot;*

So I&#39;m a little shaky on what exactly a TRY CALL should be ignoring.  It&#39;s one thing to ignore a program&#39;s exit status, and another to ignore whether the program was on disk at all.

TAKE of a BLOCK only has a definitional failure when the block is empty, so you know what TRY TAKE means.  But it may be that you should more or less never say TRY CALL, and always specifically handle the errors that arise from it.  I think this may be a common theme of definitional errors coming out of complicated functions which have more than a single way to fail.

But... in any case, it&#39;s progress.  Because we&#39;re not conflating typos or other incidental errors to those that are coming from CALL.  And I like the default that it has an error on non-zero exit statuses.</description>
    
    <lastBuildDate>Fri, 03 May 2024 21:30:55 +0000</lastBuildDate>
    <category>Errors</category>
    <atom:link href="https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Making CALL Raise a (definitional) Error For Bad Exit Codes</title>
        <dc:creator><![CDATA[hostilefork]]></dc:creator>
        <description><![CDATA[
            <aside class="quote no-group" data-username="hostilefork" data-post="1" data-topic="2068">
<div class="title">
<div class="quote-controls"></div>
<img loading="lazy" alt="" width="20" height="20" src="https://forum.rebol.info/user_avatar/forum.rebol.info/hostilefork/40/26_2.png" class="avatar"> hostilefork:</div>
<blockquote>
<p>It twists the CALL* function so that it always waits (vs. spawn a separate process and return a process ID to wait on).</p>
<p>Then it offers a /RELAX setting for getting the exit code back, if you don't want the definitional error behavior.</p>
</blockquote>
</aside>
<p>So I twisted the bootstrap executable to this notion of CALL waiting-by-default...and also treating a non-zero exit code as an error unless you said CALL/RELAX.</p>
<p>This made me wonder though: <strong>what should the result of CALL be if you don't say /RELAX</strong> ?</p>
<p>If it's still going to be a status, it will always be 0.  But this suggests you might have something to learn by testing the result.</p>
<p>A misguided person might write:</p>
<pre><code>if 1 = call ["something.exe" (filename)] [
   print "This could never happen since CALL would error on non-0 exit code"
]
</code></pre>
<p>This is where we might argue that using trash as the "useless success result" could be beneficial... <em><strong>if</strong></em> trash wasn't something you could use plain comparison on.  That was the case in Rebol2 with unsets:</p>
<pre><code>rebol2&gt;&gt; #[unset!] = #[unset!]
** Script Error: Operator is missing an argument
</code></pre>
<p>But Red and R3-Alpha allow it...</p>
<pre><code>r3-alpha&gt;&gt; #[unset] = #[unset]
== true

red&gt;&gt; #(unset) = #(unset)  ; yes, a third trivially different notation
== true
</code></pre>
<p>Ren-C has thus far followed suit, without backing away from the idea that you can compare trash to itself (or other values).</p>
<pre><code>ren-c&gt;&gt; ~ = ~
== ~true~  ; anti
</code></pre>
<p>But is this progress?</p>
<p><a href="https://forum.rebol.info/t/the-truthiness-of-trash/2180">I just posted a challenge to the value of considering trash to be neither truthy nor falsey</a>.  Note that conditional orneryness is somewhat pointless, as it provides a protection that wouldn't help the case you're supposedly distinguishing from: if CALL returned an integer unconditionally a blind conditional check would be a bug, since all integers (including zero) are truthy in the language.</p>
<p>If equality tests to trash were ornery that seems it <em>would</em> help something.  So I think it's worth asking what would be broken if you couldn't.</p>
<p>In any case...I didn't change plain CALL without /RELAX to return trash yet, but I might do so.  It has the benefit of omitting an "==" output as well due to the <a href="https://forum.rebol.info/t/console-treatment-of-void-vs-trash/2045">console suppression of trash</a>.</p>
<pre><code>&gt;&gt; call/shell "dir"
 Volume in drive C has no label.
 Volume Serial Number is 72AF-4302

 Directory of C:\Projects\ren-c\prebuilt

03/09/2024  08:32 AM    &lt;DIR&gt;          .
04/26/2024  03:36 PM    &lt;DIR&gt;          ..
11/07/2014  02:53 PM           563,560 r3-alpha
04/27/2019  04:01 PM         1,363,856 r3-linux-x64-8994d23
10/20/2023  01:23 PM         1,298,055 r3-windows-x86-8994d23.exe
10/20/2023  01:20 PM             1,656 README.md
10/22/2023  01:37 AM           864,256 rebol2.exe
03/09/2024  08:30 AM         1,607,680 red.exe
               6 File(s)      5,699,063 bytes
               2 Dir(s)  1,592,278,437,888 bytes free

&gt;&gt;
</code></pre>
<p>If 0 was left as the result, that would say "== 0" before the "&gt;&gt;"</p>
          <p><a href="https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068/2">Read full topic</a></p>
        ]]></description>
        <link>https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068/2</link>
        <pubDate>Fri, 03 May 2024 18:54:16 +0000</pubDate>
        <guid isPermaLink="false">forum.rebol.info-post-2068-2</guid>
        <source url="https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068.rss">Making CALL Raise a (definitional) Error For Bad Exit Codes</source>
      </item>
      <item>
        <title>Making CALL Raise a (definitional) Error For Bad Exit Codes</title>
        <dc:creator><![CDATA[hostilefork]]></dc:creator>
        <description><![CDATA[
            <p>Before definitional errors existed, I noticed that <a href="https://forum.rebol.info/t/the-need-to-rethink-error/1371/2">@gchiu had some uses of CALL</a> that weren't checking the return code.</p>
<pre><code>call [
    gs -sDEVICE=pngmono -o (join root "-%02d.png") -r600 (pdfname)
]

call [
    gs -sDEVICE=eps2write -sPAPERSIZE=a4
        -o (join root "-%02d.eps") (pdfname)
]
</code></pre>
<p>I wanted the default to raise an error if the <strong>gs</strong> (GhostScript) process did not return a 0 exit code.  But I wanted that error to be a result of CALL... so it would be distinct from other errors (like a typo in the code in the groups inside, <code>pfdname</code> instead of <code>pdfname</code> or whatever).</p>
<p><code>CALL</code> was already a wrapper on top of an internal <code>CALL*</code> function, so I thought "why not expand upon that?"</p>
<h2>
<a name="a-cool-enclose-of-an-augment-of-a-specialize-1" class="anchor" href="https://forum.rebol.info#a-cool-enclose-of-an-augment-of-a-specialize-1"></a>A Cool ENCLOSE of an AUGMENT of a SPECIALIZE!</h2>
<pre><code>call: enclose (
    augment (specialize :call* [wait: #]) [
        /relax "If exit code is non-zero, return the integer vs. raising error"
    ]
) func [f [frame!]] [
    let relax: f.relax
    let result: do f
    if relax or (result = 0) [
        return result
    ]
    return raise make error! compose [
        message: ["Process returned non-zero exit code:" exit-code]
        exit-code: (result)
    ]
]
</code></pre>
<p>I think that's pretty neat.</p>
<p>It twists the CALL* function so that it always waits (vs. spawn a separate process and return a process ID to wait on).</p>
<p>Then it offers a /RELAX setting for getting the exit code back, if you don't want the definitional error behavior.</p>
<p>But then, by default it will RAISE an error.   You can get that error via EXCEPT or you can do TRY CALL if you just want to ignore any errors.</p>
<h2>
<a name="issue-exposed-whos-actually-to-blame-2" class="anchor" href="https://forum.rebol.info#issue-exposed-whos-actually-to-blame-2"></a>Issue Exposed: Who's Actually To Blame?</h2>
<p>While making this I noticed that there were actually several points of failure:</p>
<ul>
<li>
<p>The guts of CALL might not be able to find the file you're asking to execute</p>
</li>
<li>
<p>The executable may run, but return a non-zero exit code</p>
</li>
<li>
<p>If you're running through CALL/SHELL and delegating to it to call a process, then the shell may have its own exit status distinct from the process you tried to call</p>
</li>
</ul>
<p>It seems there's not really any great way to untangle the return results of a shell from that of a process it executes.  <a href="https://en.wikipedia.org/wiki/Exit_status">Here's some of the informal conventions of UNIX shells</a>:</p>
<blockquote>
<p><em>"When a command is terminated by a signal whose number is N, a shell sets the variable $? to a value greater than 128. Most shells use 128+N, while ksh93 uses 256+N."</em></p>
<p><em>"If a command is not found, the shell should return a status of 127. If a command is found but is not executable, the return status should be 126."</em></p>
</blockquote>
<p>So I'm a little shaky on what exactly a TRY CALL should be ignoring.  It's one thing to ignore a program's exit status, and another to ignore whether the program was on disk at all.</p>
<p>TAKE of a BLOCK only has a definitional failure when the block is empty, so you know what TRY TAKE means.  But it may be that you should more or less never say TRY CALL, and always specifically handle the errors that arise from it.  I think this may be a common theme of definitional errors coming out of complicated functions which have more than a single way to fail.</p>
<p>But... in any case, it's progress.  Because we're not conflating typos or other incidental errors to those that are coming from CALL.  And I like the default that it has an error on non-zero exit statuses.</p>
          <p><a href="https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068/1">Read full topic</a></p>
        ]]></description>
        <link>https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068/1</link>
        <pubDate>Fri, 08 Dec 2023 02:49:41 +0000</pubDate>
        <guid isPermaLink="false">forum.rebol.info-post-2068-1</guid>
        <source url="https://forum.rebol.info/t/making-call-raise-a-definitional-error-for-bad-exit-codes/2068.rss">Making CALL Raise a (definitional) Error For Bad Exit Codes</source>
      </item>
  </channel>
</rss>
